### ISSUE TITLE
append method creating duplicate entries

### ISSUE THREAD

**Issue by KieranOB** [logentries/le_java#47]
The append method in LogentriesAppender.java is creating duplicate entries for when error messages appear. 
A customer is asking if this method is needed and if not can it be removed? to save him some data costs TT #8106 relates.

method below
protected void append(ILoggingEvent event) {
		// Render the event according to layout
		String formattedEvent = layout.doLayout(event);

		// Append stack trace if present
		IThrowableProxy error = event.getThrowableProxy();
		if (error != null) {
			formattedEvent += ExceptionFormatter.formatException(error);
		}

		// Prepare to be queued
		this.le_async.addLineToQueue(formattedEvent);
	}

**Comment by StephenHynes7** [comment]
This has been fixed in the latest version.

**Comment by udangel-r7** [comment]
test
