### ISSUE TITLE
Why the silent license change?

### ISSUE THREAD

**Issue by raupachz** [logentries/le_java#51]
In 5b74cff the license was changed from Apache to MIT.

* Why wasn't this communicated?
* I am not a lawyer, but I am **pretty** sure this is not how it works

Please revoke.

**Comment by raupachz** [comment]
See the commit for clarification.

**Comment by vilda** [comment]
Sorry for the confusion @raupachz , we got a complain from one of our users that the licensing in LICENSE and `pom.xml` does not match. We realized there's cut'n paste bug in `pom.xml` as it supposed to link to MIT.  The license was and still is MIT.

If you prefer Apache license let us know and we can make Apache-licensed release for you.
